name: Generate Pacman

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: HimaniAgrawal-10
          theme: dark
          output: dist/pacman-contribution-graph.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
