- name: Generate GitHub Logo Graph
  uses: leereilly/contribution-graph-art@v1
  with:
    github_user_name: HimaniAgrawal-10
    tetromino_count: "0"
    output_path: dist/contribution-graph-logo.svg
